# Generated by Django 4.1.2 on 2022-10-22 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='issued_to',
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='name', max_length=256),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='issue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.issue'),
        ),
    ]
