# Generated by Django 4.1.2 on 2022-10-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_remove_book_author_name_remove_book_issue_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
    ]
