# Generated by Django 4.1.3 on 2022-11-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('any', 'Any'), ('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Engineering', 'Engineering'), ('Competitive', 'Competitive')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
